#ifndef GAMEEVENTS_H
#define GAMEEVENTS_H

#include <app\event\ievent.h>

// These events are generated by the game to let the players know what's going on

// Requested to fill a grid space with the given player
class MatchCompleteEvent : public BaseEvent
{
public:
	MatchCompleteEvent(int winner) : Winner(winner) {}
	virtual const EventType& GetType() { return Type; }
	virtual const char* GetName() const { return "MatchCompleteEvent"; }

	static EventType Type;
	int Winner;
};

#endif